// <auto-generated />
using System;
using Krypteia.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Krypteia.Samples.WebApi.Migrations
{
    [DbContext(typeof(KrypteiaDbContext))]
    partial class KrypteiaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Krypteia.EntityFrameworkCore.ResetTokenEntity", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("TokenHash");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_KrypteiaResetTokens_UserId_CreatedAt");

                    b.ToTable("KrypteiaResetTokens", (string)null);
                });

            modelBuilder.Entity("Krypteia.EntityFrameworkCore.UserKeyEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedPrivateKeyBackup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MasterKeyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("MasterKeyId")
                        .HasDatabaseName("IX_KrypteiaUserKeys_MasterKeyId");

                    b.ToTable("KrypteiaUserKeys", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
